
server:
  port: 8081

kafka:
  bootstrap-servers: localhost:9092
   
#spring:
#  kafka:
#  consumer:
#    bootstrap-servers:
#      - localhost:9092
#    enable-auto-commit: true
#    auto-offset-reset: latest
#    max-poll-records: 1000
#    group-id: 'test-group'
#    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#  producer:
#    bootstrap-servers: 
#      - localhost:9092
#    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer